@echo off
echo Initializing Git...
git init
echo Adding files...
git add .
echo Committing...
git commit -m "Initial commit: Setup Fagency Backend"
echo Adding remote...
git remote add origin https://github.com/adnancholayil/fagency-backend.git
echo Renaming branch...
git branch -M main
echo Pushing to GitHub...
git push -u origin main
echo Done!
pause
